name: portable-release-actions-workflow
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
      - 'c*' # Push events to matching v*, i.e. v1.0, v20.15.10
      
jobs:
  build:
    name: Create Release
    runs-on: windows-latest
    env:
      targetZip: mikroelektronika-can-calculator-portable-${{ github.ref_name }}.zip
    steps:
      - name: installer
        shell: cmd
        run: |
          curl -L -O -J https://libstock.mikroe.com/projects/download/360/0/360_canculator__v1.1.0.0.zip &&^
          7z.exe x 360_canculator__v1.1.0.0.zip &&^
          cd 360_canculator__v1.1.0.0 &&^
          7z.exe x 1372145497_canculator__other_other.zip
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: 'zip'
          directory: "360_canculator__v1.1.0.0/CANculator"
          filename: "${{ env.targetZip }}"
          
      - name: Release prebuilt
        uses: ncipollo/release-action@v1
        with:
          artifacts: "360_canculator__v1.1.0.0/CANculator/${{ env.targetZip }}"
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}
